services:
  efbAPI:
    build: .
    restart: unless-stopped
    container_name: efbAPI
    volumes:
      - ./app:/app
    ports:
      - '65010:65010'

networks:
  default:
    external: true
    name: network